all: game mouse pong pong2 move

game: game.c
	gcc game.c -o game

mouse: mouse.c
	gcc mouse.c -o mouse

pong2: pong2.c
	gcc pong2.c -lncurses -o pong2

pong: pong.c
	gcc pong.c -lncurses -o pong

move: move.c
	gcc move.c -lncurses -o move
