all: hello box colors tty menu player

hello: hello.c
	gcc hello.c -lncurses -o hello

box: box.c
	gcc box.c -lncurses -o box

colors: colors.c
	gcc colors.c -lncurses -o colors

tty: tty.c
	gcc tty.c -lncurses -o tty

menu: menu.c
	gcc menu.c -lncurses -o menu

player: player.cpp
	g++ player.cpp -lncurses -o player
